{% set name = "ipyslides" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: 538fd3691753adfcb334d5976dbe5b18b6aca06613bf8f4ee5fbeaa033f3a086

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ipywidgets
    - markdown
    - pip
    - pillow
    - python >=3.6
  run:
    - ipywidgets
    - markdown
    - markdown-customblocks
    - pillow
    - python >=3.6

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
