{% set name = "ipyslides" %}
{% set version = "3.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: fe3e42402a51fb29d8291730434c32364a1735a2941f2c90bd55432e83d96334

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ipywidgets >=8.0.4
    - markdown
    - markdown-customblocks
    - pip
    - pillow >=9.3.0
    - python >=3.6
  run:
    - ipywidgets
    - markdown
    - markdown-customblocks
    - pillow
    - python >=3.6

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
