{% set name = "ipyslides" %}
{% set version = "5.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: 3adb7c6db93503b9d04fbad5dc4aeef8496e3533fa49ad6be479dfd68f2ba45a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # Package seems to rely on standard library collections.Iterable, which is deprecated in 3.10
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.10
    - markdown
    - markdown-customblocks
    - ipywidgets >=8.0.4
    - pillow >=9.3.0
    - anywidget ==0.9.13
    # tldraw 2.2.4 is malformed and cannot be onboarded to conda
    - tldraw >=2.2.4

    # Not listed but pip check complains
    - numpy

test:
  files:
    - ipython_test.py
  commands:
    # Skip pip check because of tldraw
    # - pip check
    - ipython ipython_test.py
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
