{% set name = "ipyslides" %}
{% set version = "3.5.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: 67e338af995f45f7627c2851125a5774d44ad4f719fe39f536904428a0d0de94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8    
    - pip    
  run:
    - python >=3.8
    - markdown
    - markdown-customblocks
    - ipywidgets >=8.0.4
    - pillow >=9.3.0
    - anywidget ==0.7.1
    - tldraw ==2.0.2

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
