{% set name = "ipyslides" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: 981f21b05003c9735887292e73439b85b1f8a321b4e115770489654f30a9cf1d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - IPython
    - ipywidgets
    - markdown
    - matplotlib-base
    - pip
    - python >=3.6
  run:
    - IPython
    - ipywidgets
    - markdown
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.6

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
